### ISSUE TITLE
support recipes steps

### ISSUE THREAD

**Issue by simonpcouch** [simonpcouch/bundle#12]
`step_umap` likely will need some custom serialization methods. 

`step_embed` and other steps from embed that use tensorflow may be worth looking into—maybe follow up with Emil here.

cc @qiushiyan, feel free to assign yourself if you end up able to make time for this. :)

**Comment by qiushiyan** [comment]
I'll start with `step_umap` in embed.

**Comment by simonpcouch** [comment]
Closed in #15🐙
